config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'

  resources :care_records do
    resource :contact, :only => [:show]
  end

  match '/contacts', to: 'contacts#index', via: 'get'

  resources :customers do
    resource :certification, :only => [:new,:show,:edit]
  end

  resources :caremanagers

  match '/index_top', to: 'care_records#index_top', via: 'get'

  resources :staffs

  root to: "home#index"  # 追記した
  get 'home/index'  # rails g controllerで作られた
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :staff
  has_many :cus_families, dependent: :destroy
  belongs_to :caremanager
  has_many :care_records, dependent: :destroy
  has_one :certification

	accepts_nested_attributes_for :cus_families, allow_destroy: true

  mount_uploader :image, ImageUploader

    extend Enumerize

    enumerize :sex, :in => [:male, :female], scope: true
    enumerize :status, :in => { enroll: 1, withdraw: 2 }, scope: :true
    enumerize :household, :in => [:alone, :elderly_only, :other], scope: true

    #validates :name, presence: true
    #validates :postal_code, presence: true, length: { is: 7 }
    #validates :home_num, length: { in: 10..11 }
    #validates :phone_num, length: { is: 11 }



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /customers
  # GET /customers.json
  def index
    @customers1 = Customer.where(status:1)
    @customers2 = Customer.where(status:2)
    @q        = Customer.search(params[:q])
    @customers = @q.result(distinct: true)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @cus_families = @customer.cus_families.all
    @caremanagers = Caremanager.where(caremanager_id: @caremanager_id)
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.cus_families.build
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to (@customer), notice: '正常に登録されました。' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: '正常に更新されました。' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: '正常に削除されました。' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:insure_num, :name, :name_kana, :sex, :birth, :postal_code, :address, :home_num, :phone_num, :fax, :mail, :reception_day, :history_of_consul, :demand, :household, :family_situation, :caremanager_id,:status, :staff_id, :image, :image_cache,
        cus_families_attributes: [:name, :relation, :living, :address, :contact, :_destroy])
    end

    def  update_customer_params
      params.require(:customer).permit(:insure_num, :name, :name_kana, :sex, :birth, :postal_code, :address, :home_num, :phone_num, :fax, :mail, :reception_day, :history_of_consul, :demand, :household, :family_situation, :caremanager_id,:status, :staff_id, :image, :image_cache,
        cus_families_attributes: [:name, :relation, :living, :address, :contact, :_destroy, :id])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
	def cus_family_title(family)
		count = family.count
		case count 
		when 1
			elem = '<th rowspan="2" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="2">'

		when 2
			elem = '<th rowspan="3" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="3">'

		when 3
			elem = '<th rowspan="4" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="4">'

		when 4
			elem = '<th rowspan="5" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="5">'

		when 5
			elem = '<th rowspan="6" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="6">'
			
		when 6
			elem = '<th rowspan="7" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="7">'

		when 7
			elem = '<th rowspan="8" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="8">'

		when 8
			elem = '<th rowspan="9" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="9">'

		when 9
			elem = '<th rowspan="10" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="10">'

		when 10
			elem = '<th rowspan="11" class="title_cusfami" style="text-align:center;"><strong>家族情報</strong></th　rowspan="11">'

		else
			elem =''

		end
		elem.html_safe
	end
end

app/views/customers/_cus_family_fields.html.erb
<fieldset>
	<%= f.label :name, "名前" %>
	<%= f.text_field :name %><br />
	<%= f.label :relation, "続柄" %>
	<%= f.text_field :relation %><br />

	<%= f.label :living, "同居・別居" %><br />
    <%= f.radio_button(:living, "together") %>
    <%= f.label :living, '同居', :value => "together" %>
    <%= f.radio_button(:living, "separate") %>
    <%= f.label :living, '別居', :value => "separate" %><br />

	<%= f.label :address, "住所" %>
	<%= f.text_field :address, :size=>"100x1" %><br />
	<%= f.label :contact, "連絡先" %>
	<%= f.text_field :contact %><br />
	<%= f.hidden_field :_destroy %>
	<%= link_to "削除", '#', class: "remove_fields" %>
</fieldset>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> ヶ所入力されていない為、登録できません。:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table class="form_cus">
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :受付日 %></td>
      <th class="input_cus">
        <%= f.date_select(
          :reception_day,
          start_year: 2010,
          end_year:   (Time.now.year),
          default:    Date.new(Time.now.year),
          use_month_numbers: true, date_separator: ' / ') %>
      </th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :被保険者番号 %></td>
    <th class="input_cus"><%= f.number_field :insure_num, placeholder: "被保険者番号" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :氏名（全角漢字） %></td>
    <th class="input_cus"><%= f.text_field :name, :size=>"30x1", placeholder: "全角漢字で入力してください。" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :氏名（全角カナ） %></td>
    <th class="input_cus"><%= f.text_field :name_kana, :size=>"30x1", placeholder: "全角カナで入力してください。" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :性別 %></td>
      <th class="input_cus">
        <%= f.radio_button(:sex, "male") %>
        <%= f.label :sex, '男性', :value => "male" %>
        <%= f.radio_button(:sex, "female") %>
        <%= f.label :sex, '女性', :value => "female" %>
      </th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :生年月日 %></td>
      <th class="input_cus">
        <%= f.date_select(
          :birth,
          start_year: 1920,
          end_year:   (Time.now.year),
          default:    Date.new(1989, 1, 1),
          use_month_numbers: true, date_separator: ' / ') %>
      </th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :郵便番号 %></td>
    <th class="input_cus"><%= f.text_field :postal_code, placeholder: "ー（ハイフン）は入れないでください。" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :住所 %></td>
    <th class="input_cus"><%= f.text_area :address, :size=>"100x2" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :Tel %></td>
    <th class="input_cus"><%= f.telephone_field :home_num %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :携帯 %></td>
    <th class="input_cus"><%= f.telephone_field :phone_num %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :FAX %></td>
    <th class="input_cus"><%= f.telephone_field :fax %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :メール %></td>
    <th class="input_cus"><%= f.email_field :mail, placeholder: "@example.co.jp" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :ケアマネージャー %></td>
    <th class="input_cus"><%= f.collection_select :caremanager_id, Caremanager.all, :id, :name%></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :家族情報 %></td>
      <th class="input_cus">
        <%= f.fields_for :cus_families do |builder| %>
        <%= render "cus_family_fields", f: builder %>
        <% end %>
        <%= link_to_add_fields "家族追加", f, :cus_families %>
      </th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :相談の経緯 %></td>
    <th class="input_cus"><%= f.text_area :history_of_consul, :size=>"100x3" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :主訴・要望 %></td>
    <th class="input_cus"><%= f.text_area :demand, :size=>"100x3" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :世帯 %></td>
      <th class="input_cus">
        <%= f.radio_button(:household, "alone") %>
        <%= f.label :household, '独身', :value => "alone" %>
        <%= f.radio_button(:household, "elderly_only") %>
        <%= f.label :household, '高齢者のみ', :value => "elderly_only" %>
        <%= f.radio_button(:household, "other") %>
        <%= f.label :household, 'その他', :value => "other" %>
      </th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :家族状況 %></td>
    <th class="input_cus"><%= f.text_area :family_situation, :size=>"100x2" %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><%= f.label :在職ステータス %></td>
    <th class="input_cus"><%= f.select :status, Customer.status.options %></th>
  </tr>
</table>

<div class="field">
  <%= image_tag @customer.image.url if @customer.image? %>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
</div>

<div class="actions">
  <%= f.submit '登録', :confirm => '登録してもよろしいですか？', :disable_with =>'登録中...' %>
</div>

<% end %>

app/views/customers/edit.html.erb
<center>
	<h1>利用者登録内容変更</h1>
</center>

<%= render 'form' %>

<%= link_to '詳細', @customer %> |
<%= link_to '戻る', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<center>
  <h1>利用者一覧</h1>
</center>

<fieldset class="search_zone"><legend>検索</legend>
  <%= search_form_for @q do |f| %>
    <%= f.label :name_start, "利用者番号：" %>
    <%= f.search_field :id_eq, placeholder: "利用者番号" %><br>
    <%= f.label :name_start, "氏名　　　：" %>
    <%= f.search_field :name_start, placeholder: "氏名（全角漢字）" %><br>
    <%= f.label :name_kana_start, "カナ　　　：" %>
    <%= f.search_field :name_kana_start, placeholder: "氏名（全角カナ）" %><br>

    <%# 検索ボタン %>
    <%= f.submit '検索' %>
  <% end %>
</fieldset>

<br>
<h3>入所者一覧</h3>
<table>
  <thead>
    <tr class="title_cus">
      <th>受付日</th>
      <th>被保険者番号</th>
      <th>名前</th>
      <th>性別</th>
      <th>生年月日</th>
      <th>自宅番号</th>
      <th>メール</th>
      <th>在籍ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers1.each do |customer| %>
      <tr>
        <td><%= customer.reception_day.strftime("%Y年%m月%d日") %></td>
        <td><%= customer.insure_num %></td>
        <td><%= link_to customer.name ,customer %></td>
        <td><%= customer.sex_text %></td>
        <td><%= customer.birth.strftime("%Y年%m月%d日") %></td>
        <td><%= customer.home_num %></td>
        <td><%= customer.mail %></td>
        <td><%= customer.status_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<table>
  <thead>
    <tr class="title_cus">
      <th>受付日</th>
      <th>被保険者番号</th>
      <th>名前</th>
      <th>性別</th>
      <th>生年月日</th>
      <th>自宅番号</th>
      <th>メール</th>
      <th>在籍ステータス</th>
    </tr>
  </thead>
<br>
<br>
<h3>退会者一覧</h3>
  <tbody>
    <% @customers2.each do |customer| %>
      <tr>
        <td><%= customer.reception_day.strftime("%Y年%m月%d日") %></td>
        <td><%= customer.insure_num %></td>
        <td><%= link_to customer.name ,customer %></td>
        <td><%= customer.sex_text %></td>
        <td><%= customer.birth.strftime("%Y年%m月%d日") %></td>
        <td><%= customer.home_num %></td>
        <td><%= customer.mail %></td>
        <td><%= customer.status_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<center>
	<h1>利用者新規登録</h1>
</center>

<%= render 'form' %>

<%= link_to '戻る', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<center>
  <h3><%= @customer.name_kana %> 　</h3>
  <h1><%= @customer.name %> 様</h1>
</center>

<table class="detail_table_cus">
  <td colspan="4" class="head_customer" style="text-align:center;">基本情報</td>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>被保険者番号</strong></td>
    <th class="input_cus"><%= @customer.insure_num %></th>
    <td class="title_cus" style="text-align:center;"><strong>受付日</strong></td>
    <th class="input_cus"><%= @customer.reception_day.strftime("%Y年%m月%d日") %></th> 
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>作成日</strong></td>
    <th class="input_cus"><%= @customer.created_at.strftime("%Y年%m月%d日 %H時%M分") %></th>
    <td class="title_cus" style="text-align:center;"><strong>更新日</strong></td>
    <th class="input_cus"><%= @customer.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>生年月日</strong></td>
    <th class="input_cus"><%= @customer.birth.strftime("%Y年%m月%d日") %></th>
    <td class="title_cus" style="text-align:center;"><strong>性別</strong></td>
    <th class="input_cus"><%= @customer.sex_text %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>郵便番号</strong></td>
    <th class="input_cus"><%= @customer.postal_code %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>住所</strong></td>
    <th colspan="3" class="input_cus"><%= @customer.address %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>自宅番号</strong></td>
    <th class="input_cus"><%= @customer.home_num %></th>
    <td class="title_cus" style="text-align:center;"><strong>携帯番号</strong></td>
    <th class="input_cus"><%= @customer.phone_num %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>FAX</strong></td>
    <th class="input_cus"><%= @customer.fax %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>メールアドレス</strong></td>
    <th colspan="3" class="input_cus"><%= @customer.mail %></th>
  </tr>
</table>

<table class="detail_table_cus">  
  <tr><%= cus_family_title(@cus_families) %>
      <th class="title_cusfami_name" style="text-align:center;"><strong>氏名</strong></th>
      <th class="title_cusfami_relation" style="text-align:center;"><strong>続柄</strong></th>
      <th class="title_cusfami_living" style="text-align:center;"><strong>同居・別居</strong></th>
      <th class="title_cusfami_address" style="text-align:center;"><strong>住所</strong></th>
      <th class="title_cusfami_contact" style="text-align:center;"><strong>連絡先</strong></th>
  </tr>
  <% @cus_families.each do |cus_family| %>
  <tr>
    <td class="input_cusfami_name"><%= cus_family.name %></td>
    <td class="input_cusfami_relation"><%= cus_family.relation %></td>
    <td class="input_cusfami_living"><%= cus_family.living %></td>
    <td class="input_cusfami_address"><%= cus_family.address %></td>
    <td class="input_cusfami_contact"><%= cus_family.contact %></td>
    </tr>
  <% end %>
</table>

<table class="detail_table_cus">
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>相談の経緯</strong></td>
    <th colspan="3" class="input_cus"><%= @customer.history_of_consul %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>主訴・要望</strong></td>
    <th colspan="3" class="input_cus"><%= @customer.demand %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>世帯</strong></td>
    <th class="input_cus"><%= @customer.household_text %></th>
    <td class="title_cus" style="text-align:center;"><strong>家族状況</strong></td>
    <th class="input_cus"><%= @customer.family_situation %></th>
  </tr>
  <tr>
    <td class="title_cus" style="text-align:center;"><strong>在籍ステータス</strong></td>
    <th class="input_cus"><%= @customer.status_text %></th>
    <td class="title_cus" style="text-align:center;"><strong style="font-size:10px;">担当ケアマネージャー</strong></td>
    <th class="input_cus"><%= @customer.caremanager.name %></th>
  </tr>
</table>



<p>
  <strong>Image:</strong>
  <% if @customer.image? %>
    <div class="thumbnail">
      <%= image_tag @customer.image.url %>
    </div>
  <% end %>
</p>



<input type="checkbox" class="check" id="checked">
<label class="menu-btn" for="checked">
  <span class="bar top"></span>
  <span class="bar middle"></span>
  <span class="bar bottom"></span>
  <span class="menu-btn__text">MENU</span>
</label>

<label class="close-menu" for="checked"></label>

<nav class="drawer-menu">
  <ul>
    <li><%= link_to '編集', edit_customer_path(@customer) %></li>
    <li><%= link_to '利用者一覧', customers_path %></li>
    <li><%= link_to '介護記録作成', new_care_record_path(@customer) %></li>
    <li><%= link_to '介護記録一覧', care_records_path %></li>
    <li><%= link_to '連絡帳一覧', contacts_path %></li>
    <li><%= link_to '削除', customers_path(@customer), method: :delete, data: { confirm: '削除すると復元できません。退職された場合は「在籍ステータス」を変更してください。それでもよろしいですか？' } %></li>
  </ul>
</nav>