config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'

  resources :care_records do
    resource :contact, :only => [:show]
  end

  match '/contacts', to: 'contacts#index', via: 'get'

  resources :customers do
    resource :certification, :only => [:new,:show,:edit]
  end

  resources :caremanagers

  match '/index_top', to: 'care_records#index_top', via: 'get'

  resources :staffs

  root to: "home#index"  # 追記した
  get 'home/index'  # rails g controllerで作られた
end

app/models/care_record.rb
class CareRecord < ActiveRecord::Base
  belongs_to :staff
  belongs_to :customer


	extend Enumerize

	enumerize :status, :in => { midstream: 1, complete: 2 }, scope: :true
end

app/controllers/care_records_controller.rb
class CareRecordsController < ApplicationController
  before_action :set_care_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /care_records
  # GET /care_records.json
  def index
    @care_records1 = CareRecord.where(status:1)
    @care_records2 = CareRecord.where(status:2)
    @q        = CareRecord.search(params[:q])
    @care_records = @q.result(distinct: true)
  end

  def index_top
    @care_records = CareRecord.where(day:Date.today)
  end

  # GET /care_records/1
  # GET /care_records/1.json
  def show
    @care_record = CareRecord.find(params[:id])
    @staffs = Staff.where(staff_id: @staff_id)

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do

        # Thin ReportsでPDFを作成
        # 先ほどEditorで作ったtlfファイルを読み込む
        report = ThinReports::Report.new(layout: "#{Rails.root}/app/pdfs/report_pdf.tlf")

        # 1ページ目を開始
        report.start_new_page

        # ブラウザでPDFを表示する
        # disposition: "inline" によりダウンロードではなく表示させている
        format.pdf {send_data report.generate,
          filename:    "#{@report.id}.pdf",
          type:        "application/pdf",
          disposition: "inline"
        }
      end
    end
  end

  # GET /care_records/new
  def new
    @care_record = CareRecord.new
  end


  # GET /care_records/1/edit
  def edit
  end


  # POST /care_records
  # POST /care_records.json
  def create
    @care_record = CareRecord.new(care_record_params)

    respond_to do |format|
      if @care_record.save
        format.html { redirect_to @care_record, notice: '作成成功。' }
        format.json { render :show, status: :created, location: @care_record }
      else
        format.html { render :new }
        format.json { render json: @care_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_records/1
  # PATCH/PUT /care_records/1.json
  def update
    respond_to do |format|
      if @care_record.update(care_record_params)
        format.html { redirect_to @care_record, notice: '更新されました。' }
        format.json { render :show, status: :ok, location: @care_record }
      else
        format.html { render :edit }
        format.json { render json: @care_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_records/1
  # DELETE /care_records/1.json
  def destroy
    @care_record.destroy
    respond_to do |format|
      format.html { redirect_to care_records_url, notice: '削除されました。' }
      format.json { head :no_content }
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_record
      @care_record = CareRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_record_params
      params.require(:care_record).permit(:day, :arrive_time, :leave_time, :blood_pressure, :pulse, :temperature, :medichine, { :treatment => [] }, :dietary_intake, :water_intake,{ :gait_training => [] }, :distance, :toilet, :stretch, :oral_stretch, :recreation, :form, :act, :detachable, { :training => [] }, :walking, :rec_name  ,:bathing, :meal_size, :contact, :opinion,:status, :staff_id_id, :customer_id, :staff_id)
    end
end

app/helpers/care_records_helper.rb
module CareRecordsHelper
end

app/views/care_records/_form.html.erb
<%= form_for(@care_record) do |f| %>
  <% if @care_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@care_record.errors.count, "error") %> 箇所入力されていない為、登録できません。:</h2>

      <ul>
      <% @care_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form_care_record">
    <tr>
      <td class="title_care_record"><%= f.label :日付 %></td>
      <th class="input_care_record"><%= f.date_select :day,{use_month_numbers: true, date_separator: ' / ' }%></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :利用者氏名 %></td>
      <th class="input_care_record"><%= f.collection_select :customer_id, Customer.all, :id, :name%></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :作成者 %></td>
      <th class="input_care_record"><%= f.collection_select :staff_id, Staff.all, :id, :name%></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :到着時間 %></td>
      <th class="input_care_record"><%= f.time_select :arrive_time %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :出発時間 %></td>
      <th class="input_care_record"><%= f.time_select :leave_time %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :血圧 %></td>
      <th class="input_care_record"><%= f.text_field :blood_pressure %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :脈 %></td>
      <th class="input_care_record"><%= f.text_field :pulse %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :体温 %></td>
      <th class="input_care_record"><%= f.text_field :temperature %>度</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :服薬 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:medichine, "有") %>
        <%= f.label :medichine, '有', :value => "有" %>
        <%= f.radio_button(:medichine, "無") %>
        <%= f.label :medichine, '無', :value => "無" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :処置 %></td>
      <th class="input_care_record">
        <%= f.check_box "treatment", {multiple: true}, "目薬",nil %>目薬
        <%= f.check_box "treatment", {multiple: true}, "軟膏",nil %>軟膏
        <%= f.check_box "treatment", {multiple: true}, "うがい手洗い",nil %>うがい手洗い
        <%= f.check_box "treatment", {multiple: true}, "口腔ケア",nil %>口腔ケア
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :食事摂取量 %></td>
      <th class="input_care_record"><%= f.text_field :dietary_intake %>割</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :水分摂取量 %></td>
      <th class="input_care_record"><%= f.text_field :water_intake %>CC</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :外での歩行練習 %></td>
      <th class="input_care_record">
        <%= f.check_box "gait_training", {multiple: true}, "見守り",nil %>見守り
        <%= f.check_box "gait_training", {multiple: true}, "杖",nil %>杖
        <%= f.check_box "gait_training", {multiple: true}, "腕組み",nil %>腕組み
        <%= f.check_box "gait_training", {multiple: true}, "シルバーカー",nil %>シルバーカー
        <%= f.check_box "gait_training", {multiple: true}, "車椅子",nil %>車椅子
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :距離 %></td>
      <th class="input_care_record"><%= f.number_field :distance %>m</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :トイレの回数 %></td>
      <th class="input_care_record"><%= f.text_field :toilet %>回</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :体操 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:stretch, "積極的参加") %>
        <%= f.label :stretch, '積極的参加', :value => "積極的参加" %>
        <%= f.radio_button(:stretch, "参加") %>
        <%= f.label :stretch, '参加', :value => "参加" %>
        <%= f.radio_button(:stretch, "消極的参加") %>
        <%= f.label :stretch, '消極的参加', :value => "消極的参加" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :口腔体操 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:oral_stretch, "積極的参加") %>
        <%= f.label :oral_stretch, '積極的参加', :value => "積極的参加" %>
        <%= f.radio_button(:oral_stretch, "参加") %>
        <%= f.label :oral_stretch, '参加', :value => "参加" %>
        <%= f.radio_button(:oral_stretch, "消極的参加") %>
        <%= f.label :oral_stretch, '消極的参加', :value => "消極的参加" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :レクリエーション %></td>
      <th class="input_care_record">
        <%= f.radio_button(:recreation, "積極的参加") %>
        <%= f.label :recreation, '積極的参加', :value => "積極的参加" %>
        <%= f.radio_button(:recreation, "参加") %>
        <%= f.label :recreation, '参加', :value => "参加" %>
        <%= f.radio_button(:recreation, "消極的参加") %>
        <%= f.label :recreation, '消極的参加', :value => "消極的参加" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :入浴 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:bathing, "一般入浴") %>
        <%= f.label :bathing, '一般入浴', :value => "一般入浴" %>
        <%= f.radio_button(:bathing, "シャワー浴") %>
        <%= f.label :bathing, 'シャワー浴', :value => "シャワー浴" %>
        <%= f.radio_button(:bathing, "清拭") %>
        <%= f.label :bathing, '清拭', :value => "清拭" %>
        <%= f.radio_button(:bathing, "洗髪") %>
        <%= f.label :bathing, '洗髪', :value => "洗髪" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :行為 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:act, "見守り") %>
        <%= f.label :act, '見守り', :value => "見守り" %>
        <%= f.radio_button(:act, "部介助") %>
        <%= f.label :act, '部介助', :value => "部介助" %>
        <%= f.radio_button(:act, "全介助") %>
        <%= f.label :act, '全介助', :value => "全介助" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :着脱 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:detachable, "見守り") %>
        <%= f.label :detachable, '見守り', :value => "見守り" %>
        <%= f.radio_button(:detachable, "部介助") %>
        <%= f.label :detachable, '部介助', :value => "部介助" %>
        <%= f.radio_button(:detachable, "全介助") %>
        <%= f.label :detachable, '全介助', :value => "全介助" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :【連絡帳記載内容】 %></td>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :施術内容 %></td>
      <th class="input_care_record">
        <%= f.check_box "training", {multiple: true}, "体操",nil %>体操
        <%= f.check_box "training", {multiple: true}, "発声",nil %>発声
        <%= f.check_box "training", {multiple: true}, "機能訓練",nil %>機能訓練
        <%= f.check_box "training", {multiple: true}, "手洗いうがい",nil %>手洗いうがい
        <%= f.check_box "training", {multiple: true}, "散歩",nil %>散歩
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :散歩 %></td>
      <th class="input_care_record">
        <%= f.radio_button(:walking, "町内") %>
        <%= f.label :walking, '町内', :value => "町内" %>
        <%= f.radio_button(:walking, "公園") %>
        <%= f.label :walking, '公園', :value => "公園" %>
        <%= f.radio_button(:walking, "その他") %>
        <%= f.label :walking, 'その他', :value => "その他" %>
        <%= f.radio_button(:walking, "不参加") %>
        <%= f.label :walking, '不参加', :value => "不参加" %>
      </th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :レクリエーション %></td>
      <th class="input_care_record"><%= f.text_field :rec_name %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :食事量 %></td>
      <th class="input_care_record">0<%= f.range_field :meal_size ,{ :size => 10,:maxlength =>15,:max=>10,:min=>0}%>10</th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :本日の連絡事項 %></td>
      <th class="input_care_record"><%= f.text_area :contact, :size=>"60x2" %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :ご家族からのご意見連絡等 %></td>
      <th class="input_care_record"><%= f.text_area :opinion, :size=>"60x2" %></th>
    </tr>
    <tr>
      <td class="title_care_record"><%= f.label :ステータス %></td>
      <th class="input_care_record"><%= f.select :status, CareRecord.status.options , :size=>"60x2"%></th>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit '作成', :confirm => '登録してもよろしいですか？', :disable_with =>'登録中...' %>
  </div>
<% end %>

app/views/care_records/contact.html.erb
<p id="notice"><%= notice %></p>

<table class="detail_table_care_record">
  <tr>
    <td class="title_care_record"><strong>日付</strong></td>
    <th class="input_care_record"><%= @care_record.day.strftime("%Y年%m月%d日") %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>血圧</strong></td>
    <th class="input_care_record"><%= @care_record.blood_pressure %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>脈</strong></td>
    <th class="input_care_record"><%= @care_record.pulse %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>体温</strong></td>
    <th class="input_care_record"><%= @care_record.temperature %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>施術内容</strong></td>
    <th class="input_care_record"><%= @care_record.training %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>散歩</strong></td>
    <th class="input_care_record"><%= @care_record.walking %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>レクリエーション</strong></td>
    <th class="input_care_record"><%= @care_record.rec_name %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>入浴</strong></td>
    <th class="input_care_record"><%= @care_record.bathing %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>食事量</strong></td>
    <th class="input_care_record"><%= @care_record.meal_size %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>連絡事項</strong></td>
    <th class="input_care_record"><%= @care_record.contact %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>家族からのご意見</strong></td>
    <th class="input_care_record"><%= @@care_record.opinion %></th>
  </tr>
</table>
<%= link_to '編集', edit_care_record_path(@care_record) %> |
<%= link_to 'Back', care_records_path %>




<input type="checkbox" class="check" id="checked">
<label class="menu-btn" for="checked">
        <span class="bar top"></span>
        <span class="bar middle"></span>
        <span class="bar bottom"></span>
        <span class="menu-btn__text">MENU</span>
</label>
<label class="close-menu" for="checked"></label>
<nav class="drawer-menu">
        <ul>
            <li><%= link_to '編集', edit_care_record_path(@care_record) %></li>
            <li><%= link_to '一覧', care_records_path %></li>
        </ul>
</nav>

app/views/care_records/edit.html.erb
<center>
	<h1>介護記録編集</h1>
</center>

<%= render 'form' %>

<%= link_to '詳細', @care_record %> |
<%= link_to '戻る', care_records_path %>

app/views/care_records/index.html.erb
<p id="notice"><%= notice %></p>

<center>
  <h1>介護記録一覧</h1>
</center>

<fieldset class="search_zone"><legend>検索</legend>
  <%= search_form_for @q do |f| %>
    <%= f.label :name_start, "日付：" %>
    <%= f.date_select :day_gt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>〜
    <%= f.date_select :day_lt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %><br/>
    <%= f.label :id, "介護記録No.：" %>
    <%= f.search_field :id_eq, placeholder: "介護記録No." %><br/>
    <%# 検索ボタン %>
    <%= f.submit '検索' %>
  <% end %>
</fieldset>
<br>
<h3>作成途中</h3>
<table>
  <thead>
    <tr class="title_care_record">
      <th>介護記録No.</th>
      <th>日付</th>
      <th>利用者氏名</th>
      <th>到着時間</th>
      <th>出発時間</th>
      <th>体温</th>
      <th>ステータス</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @care_records1.each do |care_record| %>
      <tr>
        <td><%= link_to care_record.id,care_record %></td>
        <td><%= care_record.day.strftime("%Y年%m月%d日") %></td>
        <td><%= care_record.customer.name %>様</td>
        <td><%= care_record.arrive_time.strftime("%H:%M") %></td>
        <td><%= care_record.leave_time.strftime("%H:%M") %></td>
        <td><%= care_record.temperature %>度</td>
        <td><%= care_record.status_text %></td>
        <td><%= link_to '削除', care_record, method: :delete, data: { confirm: '削除すると復元できませんがよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<table>
  <thead>
    <tr class="title_care_record">
      <th>介護記録No.</th>
      <th>日付</th>
      <th>利用者氏名</th>
      <th>到着時間</th>
      <th>出発時間</th>
      <th>体温</th>
      <th>ステータス</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <br>
  <br>
  <h3>作成完了</h3>
  <tbody>
    <% @care_records2.each do |care_record| %>
      <tr>
        <td><%= link_to care_record.id,care_record %></td>
        <td><%= care_record.day.strftime("%Y年%m月%d日") %></td>
        <td>名前が入る予定</td>
        <td><%= care_record.arrive_time.strftime("%H:%M") %></td>
        <td><%= care_record.leave_time.strftime("%H:%M") %></td>
        <td><%= care_record.temperature %>度</td>
        <td><%= care_record.status_text %></td>
        <td><%= link_to '削除', care_record, method: :delete, data: { confirm: '削除すると復元できませんがよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/care_records/index_top.html.erb
<p id="notice"><%= notice %></p>
<h1>本日の介護記録作成状況</h1>

<table>
  <thead>
    <tr class="title_care_record">
      <th>介護記録No.</th>
      <th>日付</th>
      <th>利用者氏名</th>
      <th>到着時間</th>
      <th>出発時間</th>
      <th>体温</th>
      <th>ステータス</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @care_records.each do |care_record| %>
      <tr>
        <td><%= link_to care_record.id ,care_record %></td>
        <td><%= care_record.day.strftime("%Y年%m月%d日") %></td>
        <td><%= care_record.customer.name %>様</td>
        <td><%= care_record.arrive_time.strftime("%H:%M") %></td>
        <td><%= care_record.leave_time.strftime("%H:%M") %></td>
        <td><%= care_record.temperature %>度</td>
        <td><%= care_record.status_text %></td>
        <td><%= link_to '削除', care_record, method: :delete, data: { confirm: '削除すると復元できませんがよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1 style="margin-bottom: 5px;margin-top:100px;">お知らせ</h1>
<hr style="border-top: 2px dashed ;width: 70%;float:left;"><br>
<p class="inform">現在、お知らせはありません。</p>

app/views/care_records/new.html.erb
<center>
	<h1>介護記録作成</h1>
</center>

<%= render 'form' %>

<%= link_to '戻る', care_records_path %>

app/views/care_records/show.html.erb
<p id="notice"><%= notice %></p>
<center>
  <h1><%= @care_record.customer.name %>さんの介護記録</h1>
</center>

<table class="detail_table_care_record">
  <td colspan="4" class="head_caremaneger" style="text-align:center;">基本情報</td>
  <tr>
    <td class="title_care_record"><strong>日付</strong></td>
    <th class="input_care_record"><%= @care_record.day.strftime("%Y年%m月%d日") %></th>
    <td class="title_care_record"><strong>作成者</strong></td>
    <th class="input_care_record"><%= @care_record.staff.name %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>到着時間</strong></td>
    <th class="input_care_record"><%= @care_record.arrive_time.strftime("%H:%M") %></th>
    <td class="title_care_record"><strong>出発時間</strong></td>
    <th class="input_care_record"><%= @care_record.leave_time.strftime("%H:%M") %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>血圧</strong></td>
    <th class="input_care_record"><%= @care_record.blood_pressure %></th>
    <td class="title_care_record"><strong>脈</strong></td>
    <th class="input_care_record"><%= @care_record.pulse %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>体温</strong></td>
    <th class="input_care_record"><%= @care_record.temperature %></th>
    <td class="title_care_record"><strong>服薬</strong></td>
    <th class="input_care_record"><%= @care_record.medichine %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>処置</strong></td>
    <th colspan="3" class="input_care_record"><%= @care_record.treatment %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>食事摂取量</strong></td>
    <th class="input_care_record"><%= @care_record.dietary_intake %>割</th>
    <td class="title_care_record"><strong>水分摂取量</strong></td>
    <th class="input_care_record"><%= @care_record.water_intake %>CC</th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>外での歩行練習</strong></td>
    <th colspan="3" class="input_care_record"><%= @care_record.gait_training %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>距離</strong></td>
    <th class="input_care_record"><%= @care_record.distance %>m</th>
    <td class="title_care_record"><strong>トイレの回数</strong></td>
    <th class="input_care_record"><%= @care_record.toilet %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>体操</strong></td>
    <th class="input_care_record"><%= @care_record.stretch %></th>
    <td class="title_care_record"><strong>口腔体操</strong></td>
    <th class="input_care_record"><%= @care_record.oral_stretch %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>レクリエーション</strong></td>
    <th class="input_care_record"><%= @care_record.recreation %></th>
    <td class="title_care_record"><strong>形態</strong></td>
    <th class="input_care_record"><%= @care_record.bathing %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>行為</strong></td>
    <th class="input_care_record"><%= @care_record.act %></th>
    <td class="title_care_record"><strong>着脱</strong></td>
    <th class="input_care_record"><%= @care_record.detachable %></th>
  </tr>
  <tr>
    <td class="title_care_record"><strong>ステータス</strong></td>
    <th colspan="3" class="input_care_record"><%= @care_record.status_text %></th>
  </tr>
</table>

<%= link_to "PDFで表示",care_record_path(format: "pdf") %>


<input type="checkbox" class="check" id="checked">
<label class="menu-btn" for="checked">
        <span class="bar top"></span>
        <span class="bar middle"></span>
        <span class="bar bottom"></span>
        <span class="menu-btn__text">MENU</span>
</label>
<label class="close-menu" for="checked"></label>
<nav class="drawer-menu">
        <ul>
            <li><%= link_to '編集', edit_care_record_path(@care_record) %></li>
            <li><%= link_to '一覧', care_records_path %></li>
            <li><%= link_to '連絡帳', care_record_contact_path(@care_record) %></li>
        </ul>
</nav>