config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'

  resources :care_records do
    resource :contact, :only => [:show]
  end

  match '/contacts', to: 'contacts#index', via: 'get'

  resources :customers do
    resource :certification, :only => [:new,:show,:edit]
  end

  resources :caremanagers

  match '/index_top', to: 'care_records#index_top', via: 'get'

  resources :staffs

  root to: "home#index"  # 追記した
  get 'home/index'  # rails g controllerで作られた
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>こんぺいとう基幹システム</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar">
	<div class="container">
		<div id="logo"><%=link_to "こんぺいとう基幹システム",index_top_path %></div>
	</div>
	<div>
		<ul class="header-right">
			<% if user_signed_in? %>
    			<li style="height: 65px;"><%= link_to current_user.name, edit_user_registration_path %> |</li>
    			<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete  %></li>
			<% else %>
				<li style="height: 65px;"><%= link_to "新規登録", new_user_registration_path  %> |</li>
				<li><%= link_to "ログイン", new_user_session_path %></li>
			<% end %>
		</ul>
	</div>
</header>

<% if user_signed_in? %>
	<div class="sidebar" id="accordion">
		<ul id="dropmenu">
	    	<label for="Panel1",class="sidelabel",><i class="fi-torso"> </i>スタッフ管理</label>
		    	<input type="checkbox" id="Panel1" class="on-off" />
		    		<ul>
		        		<li><%= link_to '<i class="fi-torsos"> </i>新規登録'.html_safe,new_staff_path %></li>
		        		<li><%= link_to '<i class="fi-male-female"> </i>一覧表示'.html_safe,staffs_path%></li>
		    		</ul>
	    	<label for="Panel12",class="sidelabel"><i class="fi-torso-business"> </i>ケアマネ管理</label>
	    		<input type="checkbox" id="Panel12" class="on-off" />
	    			<ul>
				        <li><%= link_to '<i class="fi-torsos-female-male"> </i>新規登録'.html_safe,new_caremanager_path%></li>
				        <li><%= link_to '<i class="fi-torsos-all"> </i>一覧表示'.html_safe,caremanagers_path%></li>
	    			</ul>
			<label for="Panel13",class="sidelabel"><i class="fi-blind"> </i>利用者管理</label>
				<input type="checkbox" id="Panel13" class="on-off" />
	    			<ul>
				        <li><%= link_to '<i class="fi-wheelchair"> </i>新規登録'.html_safe,new_customer_path%></li>
				        <li><%= link_to '<i class="fi-social-skillshare"> </i>一覧表示'.html_safe,customers_path%></li>
					</ul>
			<label for="Panel14",class="sidelabel"><i class="fi-pencil"> </i>介護記録管理</label>
				<input type="checkbox" id="Panel14" class="on-off" />
					<ul>
						<li><%= link_to '<i class="fi-clipboard-pencil"> </i>新規作成'.html_safe,new_care_record_path%></li>
						<li><%= link_to '<i class="fi-magnifying-glass"> </i>一覧表示'.html_safe,care_records_path%></li>
					</ul>
			<label for="Panel15",class="sidelabel"><i class="fi-clipboard-notes"> </i>連絡帳管理</label>
				<input type="checkbox" id="Panel15" class="on-off" />
					<ul>
						<li><%= link_to '<i class="fi-list-bullet"> </i>一覧表示'.html_safe,contacts_path%></li>
					</ul>
		</ul>
	</div>
<% end %>


<% if notice %>
	<p class="alert"><%= alert %></p>
<% end %>

<!--ここに本文-->
<div class="main">
	<%= yield %>
</div>
<!--ここまで本文-->


</body>
</html>